# Generated by Django 5.2.4 on 2025-07-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
