# Generated by Django 5.2.4 on 2025-07-18 10:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logging",
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправки",
            },
        ),
        migrations.AddField(
            model_name="logging",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
        migrations.AddField(
            model_name="logging",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 7, 18, 13, 52, 37, 341453),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
