# Generated by Django 5.2.4 on 2025-07-18 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_logging_options_logging_response_logging_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 18, 17, 26, 56, 135174), null=True, verbose_name='Последняя отправка'),
        ),
    ]
