# Generated by Django 5.2.4 on 2025-07-20 12:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_mailing_last_sent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_view_all_list", "Can watch all list")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="letter",
            options={
                "permissions": [("can_view_all_list", "Can watch all list")],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_view_all_list", "Can watch all list")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 7, 20, 15, 53, 19, 517307),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
