# Generated by Django 5.2.4 on 2025-07-20 12:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_alter_client_options_alter_letter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 7, 20, 15, 53, 24, 494970),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
