# Generated by Django 5.2.4 on 2025-07-22 11:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_alter_mailing_last_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="end_time",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 7, 22, 14, 58, 44, 13421),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
