# Generated by Django 5.2.4 on 2025-07-22 12:11

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_remove_mailing_end_time_alter_mailing_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="logging",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sended_mailings",
                to="mail.client",
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 7, 22, 15, 11, 20, 31773),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
