# Generated by Django 5.2.4 on 2025-07-22 13:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_alter_mailing_last_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logging",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_sent",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 7, 22, 13, 7, 56, 380756, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Последняя отправка",
            ),
        ),
    ]
